name: Build Docker Image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Package Version
        uses: SebRollen/toml-action@v1.2.0
        id: get_version
        with:
          file: pyproject.toml
          field: project.version
      - name: Log in to GHCR
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build the Docker image
        run: |
          docker buildx build \
            --platform linux/arm64,linux/amd64 \
            --file Dockerfile \
            --tag ghcr.io/${{ github.repository }}:latest \
            --tag ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.value }} \
            --push \
            .